# Generated by Django 5.0.4 on 2024-05-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appnt_info_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnt_info',
            name='unique_key',
        ),
    ]
