# Generated by Django 5.0.4 on 2024-05-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appnt_info_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appnt_info',
            unique_together=set(),
        ),
    ]
