# Generated by Django 5.0.4 on 2024-05-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appnt_info_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnt_info',
            name='desireDate',
        ),
        migrations.RemoveField(
            model_name='appnt_info',
            name='problemInfo',
        ),
        migrations.RemoveField(
            model_name='appnt_info',
            name='status',
        ),
    ]
