# Generated by Django 5.0.4 on 2024-05-18 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appnt_info_desiredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnt_info',
            name='desireDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appnt_info',
            name='problemInfo',
            field=models.CharField(default='Empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='appnt_info',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appnt_info',
            name='serialno',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='appnt_info',
            name='username',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
