# Generated by Django 5.0.4 on 2024-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_aboutme_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='user_image/img.jpg', upload_to='user_image/'),
        ),
    ]
