# Generated by Django 5.0.4 on 2024-05-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aboutme',
            field=models.TextField(default='Your Bio Is Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default='Firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default='Lastname', max_length=100),
        ),
    ]
