# Generated by Django 5.0.4 on 2024-05-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userprofile_aboutme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('firstname', models.CharField(default='Firstname', max_length=100)),
                ('lastname', models.CharField(default='Lastname', max_length=100)),
                ('aboutme', models.TextField(default='Your Bio Is Empty', max_length=200)),
                ('img', models.ImageField(default='user_image/default.jpg', upload_to='user_image/')),
            ],
        ),
    ]
