# Generated by Django 5.0.4 on 2024-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_doctorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='img',
            field=models.ImageField(default='user_image/img2.jpg', upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
