# Generated by Django 5.0.4 on 2024-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_doctorprofile_img_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='user_image/img2.jpg', upload_to='user_image/'),
        ),
    ]
