# Generated by Django 5.0.4 on 2024-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='aboutme',
            field=models.TextField(default='I am a dedicated and compassionate medical professional committed to providing excellent care to my patients. With years of experience in [specialty], I have honed my skills and expertise to deliver the highest standard of medical treatment. I believe in taking a holistic approach to patient care, considering not only the physical aspects but also the emotional and psychological well-being of my patients. My goal is to empower individuals to take control of their health and lead fulfilling lives. Outside of work, I enjoy staying active through hiking and yoga, as well as spending quality time with my family.', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='img',
            field=models.ImageField(default='doctor.png', upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aboutme',
            field=models.TextField(default='I am a passionate individual with a keen interest in technology and innovation. With a background in computer science, I am driven by curiosity and a desire to learn and grow. I enjoy tackling complex problems and finding creative solutions. In my free time, I love exploring the outdoors, reading science fiction novels, and experimenting with new recipes in the kitchen. I believe in continuous self-improvement and strive to make a positive impact in both my personal and professional life.', max_length=1000),
        ),
    ]
